### ISSUE TITLE
uses-sdk:minSdkVersion 19 cannot be smaller than version 21

### ISSUE THREAD

**Issue by marcio-pessoa** [StudioAdriatic/PGSGP#1]
Hi dears,

Congrats for the PGSGP, the community has long been waiting for a well mainteined Google Play Games services! <3

After update to 3.4.1 I'm getting a strange error:

```
> Task :processDebugMainManifest FAILED
/home/*****/android/build/src/debug/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [GodotPlayGamesServices.release.aar] /home/mex/.gradle/caches/transforms-3/970b45490a2361ae4cfd178ef1ac003f/transformed/jetified-GodotPlayGamesServices.release/AndroidManifest.xml as the library might be using APIs not available in 19
	Suggestion: use a compatible library with a minSdk of at most 19,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="io.cgisca.godot.gpgs" to force usage (may lead to runtime failures)

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.


FAILURE: Build failed with an exception.
```

On the last version I set SDK version to 21 on android/build/config.gradle, but now I can't understand what is happening, because SDK version 21 is set on config.gradle, but Godot is erroring android/build/src/debug/AndroidManifest.xml but this file don't have any SDK version reference.

Could you please kindly help me to solve this issue?

**Comment by kristijandraca** [comment]
Thanks for bringing this issue to my attention. I fixed it in PR #2 
Please update lib to 3.4.2

**Comment by marcio-pessoa** [comment]
I updated to 3.4.2, but it is no longer connecting to Google Play Games.
Staring a double check...

**Comment by kristijandraca** [comment]
But min SDK is no longer issue?
Do you have any log now?

**Comment by marcio-pessoa** [comment]
The min SDK issue was fixed. Thanks! <3

No records yet, I'll keep trying...

**Comment by kristijandraca** [comment]
Try with release build, make sure that you have account under testers in dev console....

**Comment by marcio-pessoa** [comment]
Nice clue, dear! The release build solved the issue. Thanks a lot!
All working fine on 3.4.2.
